
logging:
  level:
    root: WARN
    '[org.springframework.web]': WARN
    '[br.com.gbvbahia]': DEBUG
    
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:monitor
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  h2:
    scheduler:
      clean: 60000        