
info:
  app:
    name: Spring Batch Threads Life Cycle
    version: 1.0.0

logging:
  level:
    root: WARN
    '[org.springframework.web]': WARN
    '[br.com.gbvbahia]': DEBUG
    
    
spring:
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: DETECT
  mvc:
    hiddenmethod:
      filter:
        enabled: true  
        
server:
  servlet:
    context-path: '/'