info:
  app:
    name: Spring Batch Threads Life Cycle
    version: 1.0.0

logging:
  level:
    root: WARN
    '[org.springframework.web]': WARN
    '[br.com.gbvbahia]': DEBUG
    
    
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:monitor
    username: sa
    password: password
    hikari.connectionTimeout: 20000
    hikari.maximumPoolSize: 50
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: DETECT
  mvc:
    hiddenmethod:
      filter:
        enabled: true  
        
server:
  servlet:
    context-path: '/'
    
app:
  h2:
    scheduler:
      clean: 60000
  batch:
    threads:
      amount: 10 
      factor: 10
      chunks: 5
    idle: 60000
    old: 60000
  scheduler:
    batch:
      rate: 5000
      delay: 1000
      threads:
        rate: 10
        delay: 1000
    processor:
      idle:
        rate: 30000
      old:
        rate: 30000
      counter:
        rate: 1000

fake:
  scheduler:
    processor:
      url: "http://localhost:8080"
      endpoint: "/api/v1/step/threads/monitor/processor"