-- Autogenerated: do not edit this file

CREATE TABLE processor  (
	id BIGINT IDENTITY NOT NULL PRIMARY KEY ,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	name VARCHAR(255) NOT NULL,
	bearer_token VARCHAR(255) NOT NULL,
	url_to_call VARCHAR(2048) NOT NULL
) ;
