-- Autogenerated: do not edit this file

CREATE TABLE processor  (
	id BIGINT IDENTITY NOT NULL PRIMARY KEY ,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	name VARCHAR(255) NOT NULL,
	data_to_process VARCHAR(1000) NOT NULL,
	url_to_call VARCHAR(2048) NOT NULL,
	process_status VARCHAR(30) NOT NULL,
	process_result VARCHAR(255) NULL
) ;
